#include "TorchDrumLib.h"

#include "Biquad.cpp"
#include "DrumSynth.cpp"
#include "Envelope.cpp"
#include "FeatureExtraction.cpp"
#include "OnsetDetection.cpp"
#include "SynthController.cpp"
#include "Tonal.cpp"
#include "synth/modules/ExpDecayEnvelope.cpp"
#include "synth/modules/SinusoidalOscillator.cpp"
